"""add start_time to day_task

Revision ID: 41d8d51079d2
Revises: 527a7dc88a18
Create Date: 2026-06-15 19:13:37.176062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d8d51079d2'
down_revision: Union[str, Sequence[str], None] = '527a7dc88a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_task', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_task', 'start_time')
    # ### end Alembic commands ###
