"""add location fields to day_task

Revision ID: 77672ba0b22a
Revises: abdc03d7eed1
Create Date: 2026-06-19 23:21:49.124695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77672ba0b22a'
down_revision: Union[str, Sequence[str], None] = 'abdc03d7eed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_task', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('day_task', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('day_task', sa.Column('location_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_task', 'location_name')
    op.drop_column('day_task', 'lng')
    op.drop_column('day_task', 'lat')
    # ### end Alembic commands ###
