"""add trip cascade delete

Revision ID: 86b6eb2c4b31
Revises: 77672ba0b22a
Create Date: 2026-06-21 19:46:44.982789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b6eb2c4b31'
down_revision: Union[str, Sequence[str], None] = '77672ba0b22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('day_task_trip_id_fkey'), 'day_task', type_='foreignkey')
    op.create_foreign_key(None, 'day_task', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'day_task', type_='foreignkey')
    op.create_foreign_key(op.f('day_task_trip_id_fkey'), 'day_task', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###
