"""add order to day_task

Revision ID: abdc03d7eed1
Revises: 41d8d51079d2
Create Date: 2026-06-15 19:59:11.011126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdc03d7eed1'
down_revision: Union[str, Sequence[str], None] = '41d8d51079d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_task', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_task', 'order')
    # ### end Alembic commands ###
